### ISSUE TITLE
NullBooleanField soft-deprecated in Django 2.1, hard-deprecated in Django 3.1

### ISSUE THREAD

**Issue by pope1ni** [quantifiedcode/python-anti-patterns#112]
The Django correctness section mentions using `NullBooleanField` instead of `BooleanField(null=True)`. The reverse should now be advocated.

Soft-deprecation in Django 2.1 ([release notes](https://docs.djangoproject.com/en/2.1/releases/2.1/#models), [pull request](https://github.com/django/django/pull/8467))
Hard-deprecation in Django 3.1 ([release notes](https://docs.djangoproject.com/en/3.1/releases/3.1/#id2), [pull request](https://github.com/django/django/pull/12788))

**Comment by vstoykov** [comment]
Yes it's in the release notes:

> `BooleanField` can now be `null=True`. This is encouraged instead of `NullBooleanField`, which will likely be deprecated in the future.

https://docs.djangoproject.com/en/2.1/releases/2.1/#models
