### ISSUE TITLE
PDF link from previous issue not working

### ISSUE THREAD

**Issue by shimizurei** [quantifiedcode/python-anti-patterns#116]
The link from issue #102  leads to a 404.

**Comment by 01885404983** [comment]
I have added build instructions on that issue, try it out.

**Comment by duongdominhchau** [comment]
Build it yourself.

**Comment by adewes** [comment]
PDF is here now: https://github.com/quantifiedcode/python-anti-patterns/blob/master/docs/The-Little-Book-Of-Python-Anti-Patterns.pdf
