### ISSUE TITLE
NullBooleanField is deprecated

### ISSUE THREAD

**Issue by ML-Chen** [quantifiedcode/python-anti-patterns#152]
https://docs.quantifiedcode.com/python-anti-patterns/django/all/correctness/not_using_null_boolean_field.html says to use `NullBooleanField` rather than `BooleanField(null=True)`. However, `NullBooleanField` is [deprecated in Django 3.1](https://docs.djangoproject.com/en/dev/ref/models/fields/#nullbooleanfield).

**Comment by ML-Chen** [comment]
Ahh this is a duplicate of #112

**Comment by adewes** [comment]
Hey @ML-Chen, can you just open a PR for this? Would be happy to merge it and publish the new version.
