### ISSUE TITLE
n"Implementing Java-style getters ..." example, both width and length properties appear

### ISSUE THREAD

**Issue by pdehaye** [quantifiedcode/python-anti-patterns#38]

**Comment by vogelsgesang** [comment]
First of all sorry, that you did not get an answer for such a long time.

I am not able to understand the issue. I had a look at the current version as well as the [revision on April 24th](https://github.com/quantifiedcode/python-anti-patterns/blob/9cf9d4a40737be6fd69960c7993ecc888d7d7a4c/docs/correctness/implementing_java-style_getters_and_setters.rst) but I am unable to spot the word "width" in there.

**Comment by vogelsgesang** [comment]
Could you please give me a small hint, where to search? :)

**Comment by pdehaye** [comment]
[has been fixed](
https://github.com/quantifiedcode/python-anti-patterns/commit/85ad08ba1bef70e30744a9fcfa0f266e685d4e38#diff-07bb15c688990d961d6f0435dadde9a3)

**Comment by vogelsgesang** [comment]
Ah, perfect :) Thanks!
