### ISSUE TITLE
Not using forward slashes

### ISSUE THREAD

**Issue by programmdesign** [quantifiedcode/python-anti-patterns#53]
First, the "correct" example also uses backslashes. Second, the backslashes are used incorrectly, and will not compile. There are two fixes for this:
Escape the backslashes: "\\path\\to\\my\\static\\files"
Use a raw string: r"\path\to\my\static\files"

**Comment by 0xKD** [comment]
I've made this change in #55

**Comment by programmdesign** [comment]
@0xKD Thanks! That's great. I'll have a look. #closed
