### ISSUE TITLE
Property overridden for "Explicit return in __init__" anti-pattern

### ISSUE THREAD

**Issue by noisygecko** [quantifiedcode/python-anti-patterns#64]
On this page:
http://docs.quantifiedcode.com/python-code-patterns/correctness/explicit_return_in_init.html

Setting ```self.area``` in ```__init__()``` overrides the 'area' property created with the decorator.  It should be changed to something like this (renamed area variable to _area):

```python
class Rectangle:
    def __init__(self, width, height):
        self.width = width
        self.height = height
        self._area = width * height

    @property
    def area(self): # moved the logic for returning area to a separate method
        print 'in area()'
        return self._area
```

**Comment by noisygecko** [comment]
Also, the class definition should inherit from ```object```.  The code works since only the ```@property``` decorator is used (even though the documentation says that properties are only available for "new-style classes").  But if you try to add the ```@area.setter``` decorator, it will not work -- it will silently not create a setter method.

**Comment by vogelsgesang** [comment]
Thanks for reporting this bug and sorry that it take so much time until it was fixed.
I just fixed it in the source code.
It still might take some time until the fixes are online, but it should be online within the next week.
