### ISSUE TITLE
iteritems needs qualification

### ISSUE THREAD

**Issue by tacaswell** [quantifiedcode/python-anti-patterns#71]
http://docs.quantifiedcode.com/python-anti-patterns/performance/not_using_iteritems_to_iterate_large_dict.html

This needs a warning that this only applies to python 2 which is end-of-lifed.

**Comment by vogelsgesang** [comment]
And again, you are right. This best practice only applies to Python 2.
Do you want to fix it or should I do it?

**Comment by timofurrer** [comment]
See #47
