### ISSUE TITLE
super best practices needs to address python3

### ISSUE THREAD

**Issue by tacaswell** [quantifiedcode/python-anti-patterns#72]
http://docs.quantifiedcode.com/python-anti-patterns/correctness/bad_first_argument_given_to_super.html

This should address that in python3 you can use `super()` with no arguments and it will do the right thing.

**Comment by vogelsgesang** [comment]
Yes you are completely right that we should mention the possibility to call `super()` without arguments in Python3. Are you already writing a pull request or should we fix it?

Just asking in order to avoid duplicated work :)

**Comment by tacaswell** [comment]
I am not working on PRs for any of these.  I am happy to review and can take a shot at a PR if you want, but my to-do list is already longer than I can possibly complete so not sure when I will (I don't want to commit and fail to follow through).
