### ISSUE TITLE
java style getters and setters

### ISSUE THREAD

**Issue by cg-cnu** [quantifiedcode/python-anti-patterns#94]
In this [link](https://github.com/quantifiedcode/python-anti-patterns/blob/master/docs/correctness/implementing_java-style_getters_and_setters.rst#use-built-in-property-decorator)

shouldn't it be ``self.length = length`` instead of ``self._length = length`` in the class initialization?

**Comment by adewes** [comment]
@cg-cnu yeah one could do it like that, probably even makes more sense than assigning this directly because that's why the property is there in the first place (the example is a trivial one though so it doesn't matter there). Feel free to fix it an open A PR :smile:
